name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Version of xapi-cpp 
      description: In which version of xapi-cpp did this bug occur?
      options:
        - v1.0.1
        - v1.0.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: Operating system used 
      description: On which operating system and version did you encounter this bug?
      placeholder: e.g., Windows 10, macOS Ventura, Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Detailed steps on how to trigger the bug
      placeholder: please provide descrition, code snippets and so on
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: I expected this to happen
  - type: textarea
    id: error-logs
    attributes:
      label: Put here any logs (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
